version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/etc/cache
    ports:
      - 83:83
  varnish:
    build:
      context: .
      dockerfile: VarnishDockerfile
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "81:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300"
  node:
    build:
      context: .
      dockerfile: NodeDockerfile
    image: nodejs   
    restart: always
    ports:
      - "3000"